
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Program Files/JetBrains/CLion 2025.2.2/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/JetBrains/CLion 2025.2.2/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        C:/Users/Student/Downloads/hotel_manager2-main/hotel_manager2-main/cmake-build-debug/CMakeFiles/4.0.2/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: C:/Program Files/JetBrains/CLion 2025.2.2/bin/mingw/bin/g++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      Access violation
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/JetBrains/CLion 2025.2.2/bin/mingw/bin/g++.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is GNU, found in:
        C:/Users/Student/Downloads/hotel_manager2-main/hotel_manager2-main/cmake-build-debug/CMakeFiles/4.0.2/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Student/Downloads/hotel_manager2-main/hotel_manager2-main/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ehvxzp"
      binary: "C:/Users/Student/Downloads/hotel_manager2-main/hotel_manager2-main/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ehvxzp"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Student/Downloads/hotel_manager2-main/hotel_manager2-main/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ehvxzp'
        
        Run Build Command(s): "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~1/JETBRA~1/CLION2~1.2/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_c486c/fast
        Access violation
        Generator: build tool execution failed, command was: "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~1/JETBRA~1/CLION2~1.2/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_c486c/fast
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: C:/Program Files/JetBrains/CLion 2025.2.2/bin/mingw/bin/gcc.exe"
    directories:
      source: "C:/Users/Student/Downloads/hotel_manager2-main/hotel_manager2-main/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-j86qs1"
      binary: "C:/Users/Student/Downloads/hotel_manager2-main/hotel_manager2-main/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-j86qs1"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Student/Downloads/hotel_manager2-main/hotel_manager2-main/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-j86qs1'
        
        Run Build Command(s): "C:/Program Files/JetBrains/CLion 2025.2.2/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~1/JETBRA~1/CLION2~1.2/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_e4637/fast
        C:/PROGRA~1/JETBRA~1/CLION2~1.2/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_e4637.dir\\build.make CMakeFiles/cmTC_e4637.dir/build
        mingw32-make[1]: Entering directory 'C:/Users/Student/Downloads/hotel_manager2-main/hotel_manager2-main/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-j86qs1'
        Building C object CMakeFiles/cmTC_e4637.dir/testCCompiler.c.obj
        C:\\PROGRA~1\\JETBRA~1\\CLION2~1.2\\bin\\mingw\\bin\\gcc.exe   -fdiagnostics-color=always -o CMakeFiles\\cmTC_e4637.dir\\testCCompiler.c.obj -c C:\\Users\\Student\\Downloads\\hotel_manager2-main\\hotel_manager2-main\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-j86qs1\\testCCompiler.c
        mingw32-make[1]: *** [CMakeFiles\\cmTC_e4637.dir\\build.make:80: CMakeFiles/cmTC_e4637.dir/testCCompiler.c.obj] Error -1073741819
        mingw32-make[1]: Leaving directory 'C:/Users/Student/Downloads/hotel_manager2-main/hotel_manager2-main/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-j86qs1'
        mingw32-make: *** [Makefile:133: cmTC_e4637/fast] Error 2
        
      exitCode: 2
...
